import test from "node:test"; import assert from "node:assert/strict";
import { contentMetrics,testScraperRule,applyScraperRule } from "../src/toolbox/fulltext-adapter/fulltext-server.mjs";
import { parseScraperCandidate } from "../src/toolbox/fulltext-adapter/fulltext-ai.mjs";
const base={id:1,scraper_rules:".old"}; function api(){let feed={...base},writes=[];return {writes,getFeed:async()=>({...feed}),updateFeed:async(_,patch)=>{writes.push(patch);feed={...feed,...patch};return {...feed};},fetchEntryContent:async()=>"<article><p>Hello world</p><img></article>"};}
test("AI JSON parses only a compact selector",()=>{assert.equal(parseScraperCandidate('{"scraper_rules":"article .content","confidence":0.8,"reason":"ok"}').rule,"article .content");assert.throws(()=>parseScraperCandidate('{"scraper_rules":"article\\nbody"}'));});
test("test writes candidate, fetches, then restores baseline",async()=>{const a=api();const r=await testScraperRule({feedId:1,entryId:9,candidate:"article",baselineRule:".old",api:a});assert.deepEqual(a.writes,[{scraper_rules:"article"},{scraper_rules:".old"}]);assert.ok(r.metrics.textChars>0);assert.equal((await a.getFeed()).scraper_rules,".old");});
test("test failure still rolls back",async()=>{const a=api();a.fetchEntryContent=async()=>{throw new Error("fetch")};await assert.rejects(testScraperRule({feedId:1,entryId:9,candidate:"article",baselineRule:".old",api:a}));assert.equal((await a.getFeed()).scraper_rules,".old");});
test("concurrent baseline change refuses temporary write",async()=>{const a=api();await a.updateFeed(1,{scraper_rules:".other"});a.writes.length=0;await assert.rejects(testScraperRule({feedId:1,entryId:9,candidate:"article",baselineRule:".old",api:a}),{code:"CONFLICT"});assert.equal(a.writes.length,0);});
test("apply persists only after explicit confirmation",async()=>{const a=api();await applyScraperRule({feedId:1,candidate:"article",baselineRule:".old",api:a});assert.equal((await a.getFeed()).scraper_rules,"article");});
test("metrics are bounded plain text",()=>{const m=contentMetrics("<p>A <b>B</b></p><p>C</p><img>");assert.equal(m.images,1);assert.equal(m.paragraphs,2);assert.match(m.sample,/A B C/);});
